import { Calendar, MapPin, Users, DollarSign } from "lucide-react";

const PROJECTS_DATA = [
  {
    id: 1,
    title: "Amirs Residential Complex",
    folder: "a",
    category: "Residential",
    description:
      "A stunning 50-unit luxury residential development featuring modern amenities, sustainable design principles, and premium finishes throughout.",
    mainImage: "/Projects/a/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "March 2023" },
      { icon: MapPin, label: "Location", value: "Downtown District" },
      { icon: Users, label: "Client", value: "Premier Developments" },
      { icon: DollarSign, label: "Project Value", value: "$12.5M" },
    ],
    gallery: [
      { src: "/Projects/a/1.jpg", alt: "Front exterior view of Amirs Residential Complex" },
      { src: "/Projects/a/2.jpg", alt: "Modern lobby seating area at Amirs Complex" },
      { src: "/Projects/a/3.jpg", alt: "Living room interior at Amirs Residential Complex" },
      { src: "/Projects/a/4.jpg", alt: "Rooftop pool overlooking the city at Amirs Complex" },
      { src: "/Projects/a/5.jpg", alt: "Underground parking garage at Amirs Residential" },
    ],
    overview:
      "This luxury residential complex represents the pinnacle of modern urban living. Designed with sustainability and comfort in mind, the development features 50 premium units across 8 floors, each offering stunning city views and high-end finishes. The project incorporates cutting-edge green building technologies, earning it LEED Gold certification.",
    features: [
      "50 luxury residential units with premium finishes",
      "LEED Gold certified sustainable design",
      "Rooftop amenity deck with city views",
      "Underground parking with EV charging stations",
      "State-of-the-art fitness center and spa",
    ],
    specifications: [
      { label: "Total Area", value: "125,000 sq ft" },
      { label: "Floors", value: "8" },
      { label: "Unit Types", value: "1BR, 2BR, 3BR, Penthouse" },
      { label: "Duration", value: "18 months" },
      { label: "Certification", value: "LEED Gold" },
    ],
    technologies: [ "Smart home automation", "Energy-efficient HVAC", "Solar panel installation", "Rainwater harvesting" ],
    testimonial: {
      quote: "Elite Design & Structure exceeded our expectations. The quality of construction and design has set a new standard for luxury residential developments in our portfolio.",
      author: "Jennifer Martinez",
      title: "Development Director, Premier Developments",
      initials: "JM",
    },
    relatedProjectIds: [2, 3, 7],
  },
  {
    id: 2,
    title: "Tayyab Residential Renovation",
    folder: "b",
    category: "Renovation",
    description: "A comprehensive renovation of a classic residential building, transforming it into a collection of high-end, contemporary apartments with modern finishes.",
    mainImage: "/Projects/b/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "January 2024" },
      { icon: MapPin, label: "Location", value: "Metro City Central" },
      { icon: Users, label: "Client", value: "The Tayyab Family" },
      { icon: DollarSign, label: "Project Value", value: "$9.2M" },
    ],
    gallery: [
      { src: "/Projects/b/1.jpg", alt: "Renovated facade of the Tayyab Residential building" },
      { src: "/Projects/b/2.jpg", alt: "Newly designed modern lobby of the Tayyab Complex" },
      { src: "/Projects/b/3.jpg", alt: "Interior of a renovated apartment in Tayyab Complex" },
      { src: "/Projects/b/4.jpg", alt: "Modern kitchen with new appliances in a Tayyab unit" },
      { src: "/Projects/b/5.jpg", alt: "Contemporary bathroom with luxury fixtures" },
      { src: "/Projects/b/6.jpg", alt: "Close-up of the restored exterior brickwork" },
      { src: "/Projects/b/7.jpg", alt: "View from a balcony in a renovated Tayyab apartment" },
      { src: "/Projects/b/8.jpg", alt: "Common area hallway after renovation" },
    ],
    overview: "The Tayyab Complex project involved a gut renovation of a 12-story building. We preserved the classic facade while completely reimagining the interiors. The result is a series of modern, open-plan apartments with luxury finishes, smart home technology, and new, energy-efficient systems throughout, bringing a classic building into the 21st century.",
    features: [ "Complete interior gut renovation of a 12-story building", "Modernization and reconfiguration of 40 apartment units", "Installation of new energy-efficient windows and insulation", "Smart home system integration in each apartment unit", "Full restoration of the building's classic brick facade" ],
    specifications: [
      { label: "Total Area", value: "80,000 sq ft" },
      { label: "Floors", value: "12" },
      { label: "Renovated Units", value: "40" },
      { label: "Duration", value: "20 months" },
      { label: "Focus", value: "Luxury Modernization" },
    ],
    technologies: [ "Smart Lighting & Climate Control", "Keyless Entry Systems", "High-Performance Glazing", "Upgraded Electrical & Plumbing" ],
    testimonial: {
      quote: "They took our aging building and transformed it into a modern gem. The attention to detail and quality of work is evident in every corner. Our residents are thrilled.",
      author: "Mr. Tayyab",
      title: "Property Owner",
      initials: "MT",
    },
    relatedProjectIds: [1, 4, 5],
  },
  {
    id: 3,
    title: "Lahore Modern Homes",
    folder: "c",
    category: "Residential",
    description: "A multi-home new construction project in a suburban neighborhood, focusing on modern family living, energy efficiency, and functional outdoor spaces.",
    mainImage: "/Projects/c/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "September 2022" },
      { icon: MapPin, label: "Location", value: "Lahore Suburbs" },
      { icon: Users, label: "Client", value: "Suburban Estates Ltd." },
      { icon: DollarSign, label: "Project Value", value: "$7.8M" },
    ],
    gallery: [
      { src: "/Projects/c/1.jpg", alt: "Street view of the Lahore Modern Homes project" },
      { src: "/Projects/c/2.jpg", alt: "Open-concept kitchen and living area in a Lahore home" },
      { src: "/Projects/c/3.jpg", alt: "Master bedroom with en-suite bathroom" },
      { src: "/Projects/c/4.jpg", alt: "Landscaped backyard with a patio for entertaining" },
      { src: "/Projects/c/5.jpg", alt: "Exterior detail showing modern building materials" },
    ],
    overview: "This project encompassed the ground-up construction of five homes in the Lahore Modern Homes community. Each home features a custom design plan, focusing on open-concept living, gourmet kitchens, and creating a seamless indoor-outdoor flow. We managed all aspects from land development and foundation work to final interior finishes and landscaping.",
    features: [ "Ground-up construction of five single-family homes", "Custom kitchen and bathroom designs for each model", "High-standard energy-efficiency (insulation, windows)", "Professionally landscaped yards with patios", "Consistent modern aesthetic across the community" ],
    specifications: [
      { label: "Number of Homes", value: "5" },
      { label: "Avg. Area", value: "3,200 sq ft" },
      { label: "Bed/Bath", value: "4 Bed / 3.5 Bath" },
      { label: "Duration", value: "16 months" },
      { label: "Status", value: "All Units Sold" },
    ],
    technologies: [ "Modern Framing Techniques", "High-Efficiency HVAC systems", "Whole-Home Water Filtration", "Durable Exterior Cladding" ],
    testimonial: {
      quote: "BuildCraft delivered five beautiful, high-quality homes on schedule. Their project management was flawless, making the entire development process smooth and successful.",
      author: "Ali Khan",
      title: "Director, Suburban Estates Ltd.",
      initials: "AK",
    },
    relatedProjectIds: [1, 5, 7],
  },
  {
    id: 4,
    title: "Historic Building Restoration",
    folder: "d",
    category: "Renovation",
    description: "The careful and respectful restoration of a historic city landmark, preserving its unique character while incorporating modern functionality and systems.",
    mainImage: "/Projects/d/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "June 2023" },
      { icon: MapPin, label: "Location", value: "Old Town Heritage District" },
      { icon: Users, label: "Client", value: "City Heritage Trust" },
      { icon: DollarSign, label: "Project Value", value: "$8.5M" },
    ],
    gallery: [
      { src: "/Projects/d/1.jpg", alt: "Restored facade of the historic Grand Hotel" },
      { src: "/Projects/d/2.jpg", alt: "Intricate details of the restored interior crown molding" },
      { src: "/Projects/d/3.jpg", alt: "Grand ballroom of the hotel restored to its former glory" },
      { src: "/Projects/d/4.jpg", alt: "Modern reception area blended with historic architecture" },
    ],
    overview: "This project focused on the meticulous restoration of The Grand Hotel, a 19th-century landmark. Our team worked closely with historical preservation societies to ensure every detail, from the facade to the interior plasterwork, was authentically restored. Modern electrical, plumbing, and HVAC systems were carefully integrated to meet current standards without compromising the building's historical integrity.",
    features: [ "Authentic restoration of historical facade and interiors", "Structural reinforcement and stabilization", "Integration of modern MEP systems", "Custom millwork to match original designs", "Compliance with historical preservation guidelines" ],
    specifications: [
      { label: "Building Age", value: "Circa 1890" },
      { label: "Total Area", value: "45,000 sq ft" },
      { label: "Protected Status", value: "Grade I Listed" },
      { label: "Duration", value: "22 months" },
      { label: "Awards", value: "Heritage Preservation Award 2023" },
    ],
    technologies: [ "Laser Cleaning for Facades", "Non-invasive Surveying (GPR)", "Modern HVAC Integration", "Historically Accurate Window Restoration" ],
    testimonial: {
      quote: "The level of craftsmanship and respect for the building's history was truly remarkable. BuildCraft has given this landmark a new lease on life for generations to come.",
      author: "Eleanor Vance",
      title: "Chair, City Heritage Trust",
      initials: "EV",
    },
    relatedProjectIds: [1, 2, 6],
  },
  {
    id: 5,
    title: "Maple Creek Townhomes",
    folder: "e",
    category: "Residential",
    description: "An exclusive community of 20 modern townhomes, offering spacious living with private gardens and premium community amenities.",
    mainImage: "/Projects/e/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "August 2023" },
      { icon: MapPin, label: "Location", value: "Maple Creek Estates" },
      { icon: Users, label: "Client", value: "Oakridge Properties" },
      { icon: DollarSign, label: "Project Value", value: "$11.2M" },
    ],
    gallery: [
      { src: "/Projects/e/1.jpg", alt: "Exterior view of a row of Maple Creek townhomes" },
      { src: "/Projects/e/2.jpg", alt: "Interior of a modern townhome living room" },
      { src: "/Projects/e/3.jpg", alt: "Sleek kitchen with a breakfast island" },
      { src: "/Projects/e/4.jpg", alt: "Private backyard patio area of a townhome" },
      { src: "/Projects/e/5.jpg", alt: "Community clubhouse and swimming pool" },
      { src: "/Projects/e/6.jpg", alt: "Master bedroom with large windows" },
    ],
    overview: "Maple Creek Townhomes is a new residential development designed for modern families. Each of the 20 homes features three levels of living space, a private garage, and a backyard garden. The community also includes a shared clubhouse, pool, and playground, fostering a strong sense of community.",
    features: [ "20 multi-level townhomes with private garages", "Open-concept floor plans with high ceilings", "Private gardens and patio spaces for each unit", "Community clubhouse with fitness center and pool", "High-end finishes and gourmet kitchens" ],
    specifications: [
      { label: "Number of Units", value: "20" },
      { label: "Avg. Area", value: "2,200 sq ft" },
      { label: "Bed/Bath", value: "3 Bed / 2.5 Bath" },
      { label: "Duration", value: "14 months" },
      { label: "Amenities", value: "Clubhouse, Pool, Playground" },
    ],
    technologies: ["Energy Star Appliances", "Zoned HVAC systems", "Durable Fiber Cement Siding", "Community-wide Wi-Fi"],
    testimonial: {
      quote: "They created a wonderful, high-quality community from the ground up. The design is modern yet practical, and our buyers have been extremely happy.",
      author: "Robert Frost",
      title: "CEO, Oakridge Properties",
      initials: "RF",
    },
    relatedProjectIds: [1, 3, 6],
  },
  {
    id: 6,
    title: "Grand Community Mosque",
    folder: "f",
    category: "Community",
    description: "A landmark project constructing a new mosque to serve as a spiritual and community hub, featuring traditional design with modern construction techniques.",
    mainImage: "/Projects/f/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "December 2023" },
      { icon: MapPin, label: "Location", value: "Community Park District" },
      { icon: Users, label: "Client", value: "Anjuman-E-Islamia Trust" },
      { icon: DollarSign, label: "Project Value", value: "$15.0M" },
    ],
    gallery: [
      { src: "/Projects/f/1.jpg", alt: "Exterior view of the Grand Community Mosque with dome and minaret" },
      { src: "/Projects/f/2.jpg", alt: "Spacious main prayer hall with intricate carpet design" },
      { src: "/Projects/f/3.jpg", alt: "Detail of the grand dome's interior calligraphy" },
      { src: "/Projects/f/4.jpg", alt: "Modern ablution (wudu) area with marble finishes" },
      { src: "/Projects/f/5.jpg", alt: "The mosque illuminated at night" },
    ],
    overview: "The Grand Community Mosque is a new-build project designed to be a beacon of peace and a center for community life. The architecture blends traditional Islamic geometric patterns and calligraphy with modern, durable materials. The complex includes a large main prayer hall, a separate prayer area for ladies, a library, classrooms for religious education, and a multi-purpose community hall.",
    features: [ "Large main prayer hall with a capacity for 1,500 worshippers", "Separate, dedicated prayer hall and entrance for ladies", "Iconic 120-foot tall minaret and a 60-foot diameter main dome", "Intricate Islamic calligraphy and geometric tilework throughout", "Community wing with library, classrooms, and event hall" ],
    specifications: [
      { label: "Total Area", value: "90,000 sq ft" },
      { label: "Prayer Capacity", value: "2,000+" },
      { label: "Minaret Height", value: "120 ft" },
      { label: "Dome Diameter", value: "60 ft" },
      { label: "Duration", value: "30 months" },
    ],
    technologies: [ "State-of-the-art Sound System for Adhan and sermons", "Energy-efficient LED lighting system", "Underfloor radiant heating in prayer halls", "Modern, accessible ablution facilities" ],
    testimonial: {
      quote: "Elite Design & Structure have built more than a mosque; they have built a beautiful home for our community. Their professionalism and quality are second to none.",
      author: "Dr. Ibrahim Khan",
      title: "Chairman, Anjuman-E-Islamia Trust",
      initials: "IK",
    },
    relatedProjectIds: [1, 4, 7],
  },
  {
    id: 7,
    title: "Dr. Amir's Custom Residence",
    folder: "g",
    category: "Residential",
    description: "A bespoke luxury home designed and built to the client's exact specifications, featuring an infinity pool, home theater, and panoramic views.",
    mainImage: "/Projects/g/1.jpg",
    stats: [
      { icon: Calendar, label: "Completed", value: "May 2024" },
      { icon: MapPin, label: "Location", value: "Hilltop Estates" },
      { icon: Users, label: "Client", value: "Dr. Amir" },
      { icon: DollarSign, label: "Project Value", value: "$4.5M" },
    ],
    gallery: [
      { src: "/Projects/g/1.jpg", alt: "Front exterior of Dr. Amir's modern custom residence" },
      { src: "/Projects/g/2.jpg", alt: "Infinity pool overlooking the valley" },
      { src: "/Projects/g/3.jpg", alt: "Open-plan living area with floor-to-ceiling windows" },
      { src: "/Projects/g/4.jpg", alt: "State-of-the-art home theater with tiered seating" },
      { src: "/Projects/g/5.jpg", alt: "Gourmet kitchen with marble countertops" },
      { src: "/Projects/g/6.jpg", alt: "Master bathroom with a freestanding tub and walk-in shower" },
    ],
    overview: "This project was a true collaboration with the client, Dr. Amir, to create his dream home. Every element was custom-designed, from the architectural layout that maximizes views to the specific interior finishes. The result is a one-of-a-kind residence that perfectly balances modern luxury with comfortable, personal living spaces.",
    features: [
      "Custom architectural design from concept to completion",
      "Infinity-edge swimming pool with panoramic views",
      "Dedicated soundproof home cinema room",
      "Gourmet chef's kitchen with high-end appliances",
      "Extensive use of natural stone and hardwood",
      "Fully integrated smart home system",
    ],
    specifications: [
      { label: "Total Area", value: "6,500 sq ft" },
      { label: "Bed/Bath", value: "5 Bed / 6 Bath" },
      { label: "Lot Size", value: "2 Acres" },
      { label: "Garage", value: "3-Car" },
      { label: "Duration", value: "15 months" },
    ],
    technologies: ["Full Smart Home Integration (Lutron, Sonos)", "Geothermal Heating & Cooling", "Advanced Security & Surveillance", "Automated Window Shades"],
    testimonial: {
      quote: "They turned my vision into a home that is more beautiful than I could have ever imagined. The craftsmanship is impeccable, and the process was a pleasure.",
      author: "Dr. Amir",
      title: "Homeowner",
      initials: "DA",
    },
    relatedProjectIds: [1, 3, 5],
  },
];

export default PROJECTS_DATA;